spring:
  datasource:
    url: jdbc:h2:mem:file-storage
    driverClassName: org.h2.Driver
    username: admin
    password:
  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 128KB
      max-request-size: 128KB
  http:
    log-request-details: true
file_store:
  path:
    root: /home/kostic/tmp
logging:
  level:
    root: ERROR
    org.springframework: ERROR
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: ERROR